# Generated by Django 4.1.5 on 2023-01-09 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
