# Generated by Django 4.1.5 on 2023-01-10 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0003_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='view',
            name='ip',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
