# Generated by Django 4.1.5 on 2023-01-09 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_subscription_channel_subscribering_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='subscribering',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
